### PR TITLE
fix: Align OpenTelemetry modules to v1.44.0 to restore develop build

### PR DESCRIPTION
**Pull request by bjcoombs**
## Summary

The Go **Build** on `develop` is broken (also failing **Generate SBOM** and, in cascade, **Trivy Container Image Scan**). The dependabot go-dependencies group bump (#2231) raised the otel core, `otlptrace`, `sdk`, and `trace` requires to v1.44.0 but left the `replace` pins and two `require` stragglers (`otlptracegrpc`, `sdk/metric`) at v1.43.0.

This violated the invariant already documented in `go.mod` - *"Pin must match the otlptrace exporter version."* The v1.44.0 `otlptrace` exporter references `attribute.BYTESLICE` / `attribute.SLICE` / `AsByteSlice` / `AsSlice`, which the replace-pinned v1.43.0 `attribute` package does not provide:

```
otlptrace@v1.44.0/internal/tracetransform/attribute.go:90:17: undefined: attribute.BYTESLICE
```

## Changes Made

- `go.mod`: bump the five otel `replace` pins and the two `require` stragglers (`otlptracegrpc`, `sdk/metric`) from v1.43.0 -> v1.44.0, restoring a single consistent otel version across the whole constellation
- Update the rationale comment (the version-matching note now references the v1.44.0 attribute APIs)
- `go.sum`: `go mod tidy` floats `genproto/googleapis/api`+`/rpc` forward to the revision `otlptracegrpc` v1.44.0 requires

## Testing

- `go build ./...` - **clean** (was failing with the `attribute.BYTESLICE` undefined error before this change)
- `go mod tidy` reconciles with no residual v1.43.0 otel references

## Risk Assessment

Low. Patch-level alignment within otel v1.44.x; the requires were already at v1.44.0, this brings the replaces and two stragglers into line. No application code changes.

## Evidence

- Root cause introduced by #2231 (dependabot go-dependencies group bump)
- Failing checks on develop HEAD (`acd8cd65`): Build, Generate SBOM, Trivy Container Image Scan

### CODE REVIEW

**Comment by bjcoombs** [comment]
Added a second commit: aligning otel to v1.44.0 surfaced a runtime resource **schema URL conflict** (SDK `resource.Default()` at schema 1.41.0 vs code's semconv v1.40.0 at 1.40.0) that the broken v1.43.0 build could never reach. This broke `TestContainer_initTracer_Disabled` across all five app containers. Bumped the four `shared/platform/observability` files from semconv v1.40.0 → v1.41.0. Verified locally: `go build ./...` clean, all five initTracer tests pass, observability package tests pass.
